/**
 * @mindtris/design-system
 * Re-export components and theme APIs
 */

export { cn } from './lib/utils'

// Animation utilities
export {
  getTransitionClass,
  shouldReduceMotion,
  getRespectfulDuration,
  createKeyframe,
} from './lib/animation-utils'

// Focus utilities
export {
  getFocusableElements,
  focusFirstElement,
  focusLastElement,
  focusNextElement,
  focusPreviousElement,
  isFocusable,
} from './lib/focus-utils'

// Variant utilities
export {
  createVariants,
  variantClassNames,
} from './lib/variant-utils'
export type { VariantConfig } from './lib/variant-utils'

// Accessibility utilities
export {
  generateId,
  getAriaLabel,
  getAriaDescribedBy,
  announceToScreenReader,
  isVisibleToScreenReader,
  getAccessibleName,
} from './lib/a11y-utils'

// Performance utilities
export {
  throttle,
  debounce,
  raf,
  doubleRaf,
} from './lib/performance-utils'

// Validation patterns
export {
  required,
  email,
  minLength,
  maxLength,
  pattern,
  numberRange,
  min,
  max,
  url,
  combine,
  conditional,
  createRule,
} from './lib/validation-patterns'
export type { ValidationRule } from './lib/validation-patterns'

// Component API patterns
export type {
  StandardComponentProps,
  PolymorphicProps,
  VariantComponentProps,
  FormComponentProps,
  InteractiveComponentProps,
} from './lib/component-api-patterns'
export { createStandardProps } from './lib/component-api-patterns'

// Contexts (layout/sidebar state)
export { default as AppProvider, useAppProvider } from './contexts/app-provider'

// Hooks
export {
  useWindowWidth,
  useMediaQuery,
  useBreakpoint,
  useClickOutside,
  useDebounce,
  usePrefersReducedMotion,
  useTransitionState,
  useFocusTrap,
  useFocusReturn,
  useAsyncState,
  useToggle,
  useCounter,
  useAriaLive,
  useThrottle,
  useFormValidation,
} from './hooks'
export type {
  TransitionState,
  UseTransitionStateOptions,
  AsyncState,
  UseAsyncStateOptions,
  UseCounterOptions,
  FieldValidation,
  UseFormValidationOptions,
} from './hooks'

// Phase B: Theme engine exports
export { useThemeManager } from './theme/use-theme-manager'
export { applyThemePreset, applyImportedTheme, applyRadius, handleColorChange, resetTheme } from './theme/apply-theme'
export { colorThemes } from './theme/theme-data'
export { themePresets } from './theme/presets'
export { radiusOptions, baseColors, colorGroups } from './theme/constants'
export type {
  ThemePreset,
  ColorTheme,
  ImportedTheme,
  ThemeStyles,
  ThemeStyleProps,
  ColorGroup,
  CustomThemeArtifactV1,
  CustomThemeBase,
  CustomThemeOverrides,
  CustomThemeLayoutOverrides,
} from './theme/types'

// Phase B: ThemeCustomizer component
export { ThemeCustomizer } from './components/theme-customizer'
export { ThemeTab } from './components/theme-customizer/theme-tab'
export { LayoutTab } from './components/theme-customizer/layout-tab'
export { ImportModal } from './components/theme-customizer/import-modal'
export { ColorsPanel } from './components/theme-customizer/colors-panel'
export { ColorInput } from './components/theme-customizer/color-input'
export { TypographyPanel } from './components/theme-customizer/typography-panel'
export { OtherPanel } from './components/theme-customizer/other-panel'

// Phase C: design-system UI components (use in customizer and app)
export {
  AccordionGroup,
  Accordion,
  Alert,
  Avatar,
  AvatarGroup,
  Badge,
  Breadcrumb,
  Button,
  ButtonGroup,
  ButtonGroupItem,
  ButtonGroupSeparator,
  ToggleGroup,
  ToggleGroupItem,
  Card,
  DashboardCard,
  StatCard,
  SimpleCard,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  Chip,
  Input,
  Checkbox,
  Radio,
  Switch,
  Select,
  DropdownSelect,
  ClassicDropdown,
  DropdownIconMenu,
  DropdownMenuSectionLabel,
  DropdownMenuAction,
  DropdownMenu,
  DropdownMenuPortal,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
  Logo,
  SidebarLinkGroup,
  SidebarLink,
  Popover,
  PopoverTrigger,
  PopoverAnchor,
  PopoverContent,
  Dialog,
  DialogTrigger,
  DialogPortal,
  DialogClose,
  DialogOverlay,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  Drawer,
  DrawerTrigger,
  DrawerPortal,
  DrawerClose,
  DrawerOverlay,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
  Modal,
  Sheet,
  SheetTrigger,
  SheetPortal,
  SheetClose,
  SheetOverlay,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
  HoverCard,
  HoverCardTrigger,
  HoverCardContent,
  CardDecorator,
  Progress,
  Slider,
  LoadingSpinner,
  Skeleton,
  CardSkeleton,
  TableSkeleton,
  ErrorBoundary,
  ErrorFallback,
  useErrorHandler,
  Calendar,
  Sidebar,
  Header,
  Navbar,
  ResponsiveDialog,
  Pagination,
  Tabs,
  TabsWithContainer,
  TabsRoot,
  TabsList,
  TabsTrigger,
  TabsContent,
  CollapsibleSection,
  ThemeToggleIcon,
  // Tooltip (simple)
  ButtonTooltip,
  Tooltip,
  // Tooltip (Radix primitives)
  RadixTooltip,
  RadixTooltipTrigger,
  RadixTooltipContent,
  RadixTooltipProvider,
  Separator,
  Label,
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandSeparator,
  CommandShortcut,
  ScrollArea,
  ScrollBar,
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
  Toggle,
  toggleVariants,
  Toaster,
  toast,
  toastSemantic,
  SelectRoot,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  Icon,
  createIcon,
  DropdownProfile,
} from './components/ui'
export type {
  AccordionGroupProps,
  AccordionGroupItem,
  AccordionGroupSingleProps,
  AccordionGroupMultipleProps,
  AccordionProps,
  AlertProps,
  AlertVariant,
  AvatarProps,
  AvatarSize,
  AvatarStatus,
  AvatarGroupProps,
  AvatarGroupOverlap,
  BadgeProps,
  BadgeVariant,
  BadgeSize,
  BreadcrumbProps,
  BreadcrumbItem,
  BreadcrumbSeparator,
  ButtonProps,
  ButtonVariant,
  ButtonSize,
  ButtonGroupProps,
  ButtonGroupItemProps,
  ButtonGroupSeparatorProps,
  ButtonGroupOrientation,
  ToggleGroupProps,
  ToggleGroupItemProps,
  ToggleGroupType,
  ToggleGroupOrientation,
  ChipProps,
  ChipSize,
  ChipVariant,
  InputProps,
  CheckboxProps,
  RadioProps,
  SwitchProps,
  SelectProps,
  DropdownSelectProps,
  DropdownOption,
  DropdownAlign,
  DropdownMenuAlign,
  DropdownIconMenuProps,
  DropdownMenuActionProps,
  DropdownMenuProps,
  DropdownMenuTriggerProps,
  DropdownMenuPortalProps,
  DropdownMenuContentProps,
  DropdownMenuGroupProps,
  DropdownMenuLabelProps,
  DropdownMenuItemProps,
  DropdownMenuCheckboxItemProps,
  DropdownMenuRadioGroupProps,
  DropdownMenuRadioItemProps,
  DropdownMenuSeparatorProps,
  DropdownMenuSubProps,
  DropdownMenuSubTriggerProps,
  DropdownMenuSubContentProps,
  PopoverProps,
  PopoverTriggerProps,
  PopoverAnchorProps,
  PopoverContentProps,
  DialogProps,
  DialogTriggerProps,
  DialogPortalProps,
  DialogCloseProps,
  DialogOverlayProps,
  DialogContentProps,
  DialogHeaderProps,
  DialogFooterProps,
  DialogTitleProps,
  DialogDescriptionProps,
  DrawerProps,
  DrawerTriggerProps,
  DrawerPortalProps,
  DrawerCloseProps,
  DrawerOverlayProps,
  DrawerContentProps,
  DrawerHeaderProps,
  DrawerFooterProps,
  DrawerTitleProps,
  DrawerDescriptionProps,
  ModalProps,
  ModalSize,
  SheetProps,
  SheetTriggerProps,
  SheetPortalProps,
  SheetCloseProps,
  SheetOverlayProps,
  SheetContentProps,
  SheetContentSide,
  SheetHeaderProps,
  SheetFooterProps,
  SheetTitleProps,
  SheetDescriptionProps,
  TableProps,
  TableHeaderProps,
  TableBodyProps,
  TableFooterProps,
  TableRowProps,
  TableHeadProps,
  TableCellProps,
  TableCaptionProps,
  HoverCardProps,
  HoverCardTriggerProps,
  HoverCardContentProps,
  CardDecoratorProps,
  ProgressProps,
  ProgressVariant,
  ProgressSize,
  SliderProps,
  SliderVariant,
  SliderSize,
  CardProps,
  ResponsiveDialogProps,
  ResponsiveDrawerDirection,
  ResponsiveDialogMode,
  PaginationProps,
  PaginationVariant,
  TabsWithContainerItem,
  SkeletonProps,
  SkeletonTone,
  SkeletonRadius,
  SkeletonLineSize,
  TabsRootProps,
  TabsListProps,
  TabsTriggerProps,
  TabsContentProps,
  SeparatorProps,
  LabelProps,
  CommandProps,
  CommandDialogProps,
  ScrollAreaProps,
  ScrollAreaViewportProps,
  ScrollBarProps,
  ResizablePanelGroupProps,
  ResizablePanelProps,
  ResizableHandleProps,
  ToggleProps,
  ToggleSize,
  ToggleVariant,
  ToasterProps,
  SelectRootProps,
  SelectTriggerProps,
  SelectContentProps,
  SelectItemProps,
  SelectLabelProps,
  SelectSeparatorProps,
  TooltipProps,
  ButtonTooltipProps,
  RadixTooltipProps,
  RadixTooltipTriggerProps,
  RadixTooltipContentProps,
  RadixTooltipProviderProps,
  IconProps,
  DropdownProfileProps,
} from './components/ui'

// Icon constants
export {
  ICON_DEFAULT_SIZE,
  ICON_DEFAULT_STROKE_WIDTH,
  ICON_SIZES,
} from './lib/icon-constants'
export type { IconSize } from './lib/icon-constants'

// Phase C: design-system sections (composite blocks) — add section exports as built
export { Header as SectionHeader } from './components/sections'
export type { HeaderProps as SectionHeaderProps, HeaderLink } from './components/sections'

// Phase C: design-system layouts
export { Container, Page, Section, Grid, Stack } from './components/layouts'
export type { ContainerProps, PageProps, SectionProps, GridProps, StackProps } from './components/layouts'
