/**
 * @mindtris/design-system
 * Re-export components and theme APIs
 */

export { cn } from './lib/utils'

// Animation utilities
export {
  getTransitionClass,
  shouldReduceMotion,
  getRespectfulDuration,
  createKeyframe,
} from './lib/animation-utils'

// Focus utilities
export {
  getFocusableElements,
  focusFirstElement,
  focusLastElement,
  focusNextElement,
  focusPreviousElement,
  isFocusable,
} from './lib/focus-utils'

// Variant utilities
export {
  createVariants,
  variantClassNames,
} from './lib/variant-utils'
export type { VariantConfig } from './lib/variant-utils'

// Accessibility utilities
export {
  generateId,
  getAriaLabel,
  getAriaDescribedBy,
  announceToScreenReader,
  isVisibleToScreenReader,
  getAccessibleName,
} from './lib/a11y-utils'

// Performance utilities
export {
  throttle,
  debounce,
  raf,
  doubleRaf,
} from './lib/performance-utils'

// Validation patterns
export {
  required,
  email,
  minLength,
  maxLength,
  pattern,
  numberRange,
  min,
  max,
  url,
  combine,
  conditional,
  createRule,
} from './lib/validation-patterns'
export type { ValidationRule } from './lib/validation-patterns'

// Component API patterns
export type {
  StandardComponentProps,
  PolymorphicProps,
  VariantComponentProps,
  FormComponentProps,
  InteractiveComponentProps,
} from './lib/component-api-patterns'
export { createStandardProps } from './lib/component-api-patterns'

// Contexts (root-level re-export for reliable resolution from consumers' node_modules)
export { AppProvider, useAppProvider } from './app-provider-primitives'

// Hooks
export {
  useWindowWidth,
  useMediaQuery,
  useBreakpoint,
  useClickOutside,
  useDebounce,
  usePrefersReducedMotion,
  useTransitionState,
  useFocusTrap,
  useFocusReturn,
  useAsyncState,
  useToggle,
  useCounter,
  useAriaLive,
  useThrottle,
  useFormValidation,
} from './hooks'
export type {
  TransitionState,
  UseTransitionStateOptions,
  AsyncState,
  UseAsyncStateOptions,
  UseCounterOptions,
  FieldValidation,
  UseFormValidationOptions,
} from './hooks'

// Phase B: Theme engine exports
export { useThemeManager } from './theme/use-theme-manager'
export { applyThemePreset, applyImportedTheme, applyRadius, handleColorChange, resetTheme } from './theme/apply-theme'
export { colorThemes } from './theme/theme-data'
export { themePresets } from './theme/presets'
export { radiusOptions, baseColors, colorGroups } from './theme/constants'
export type {
  ThemePreset,
  ColorTheme,
  ImportedTheme,
  ThemeStyles,
  ThemeStyleProps,
  ColorGroup,
  CustomThemeArtifactV1,
  CustomThemeBase,
  CustomThemeOverrides,
  CustomThemeLayoutOverrides,
} from './theme/types'

// Phase B: ThemeCustomizer (root-level re-export for reliable resolution from consumers' node_modules)
export { ThemeCustomizer, ThemeTab, LayoutTab, ImportModal, ColorsPanel, ColorInput, TypographyPanel, OtherPanel } from './theme-customizer-primitives'
export type { ThemeCustomizerSection } from './theme-customizer-primitives'

// Phase C: design-system UI components (root-level re-export for reliable resolution from consumers' node_modules)
export {
  AccordionGroup,
  Accordion,
  Alert,
  AspectRatio,
  Avatar,
  AvatarImage,
  AvatarFallback,
  AvatarBadge,
  AvatarGroup,
  AvatarGroupCount,
  Badge,
  Breadcrumb,
  Button,
  ButtonGroup,
  ButtonGroupItem,
  ButtonGroupSeparator,
  ToggleGroup,
  ToggleGroupItem,
  Card,
  DashboardCard,
  StatCard,
  SimpleCard,
  CardHeader,
  CardTitle,
  CardDescription,
  CardAction,
  CardImage,
  CardContent,
  CardFooter,
  Chip,
  Input,
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
  InputOTPSingle,
  FileInput,
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
  InputGroupTextarea,
  Checkbox,
  Radio,
  RadioGroup,
  RadioGroupItem,
  Switch,
  Select,
  NativeSelect,
  Field,
  Empty,
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
  Combobox,
  Menubar,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarItem,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarLabel,
  MenubarSeparator,
  MenubarShortcut,
  MenubarGroup,
  MenubarPortal,
  MenubarSub,
  MenubarSubTrigger,
  MenubarSubContent,
  ContextMenu,
  ContextMenuTrigger,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuCheckboxItem,
  ContextMenuRadioGroup,
  ContextMenuRadioItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuGroup,
  ContextMenuPortal,
  ContextMenuSub,
  ContextMenuSubTrigger,
  ContextMenuSubContent,
  Textarea,
  RichTextEditor,
  DropdownSelect,
  ClassicDropdown,
  DropdownIconMenu,
  DropdownMenuSectionLabel,
  DropdownMenuAction,
  DropdownMenu,
  DropdownMenuPortal,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
  Logo,
  SidebarLinkGroup,
  SidebarLink,
  SidebarMenuButton,
  SidebarHeader,
  SidebarFooter,
  SidebarContent,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarInput,
  SidebarSeparator,
  Popover,
  PopoverTrigger,
  PopoverAnchor,
  PopoverContent,
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
  Dialog,
  DialogTrigger,
  DialogPortal,
  DialogClose,
  DialogOverlay,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  Drawer,
  DrawerTrigger,
  DrawerPortal,
  DrawerClose,
  DrawerOverlay,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
  Modal,
  Sheet,
  SheetTrigger,
  SheetPortal,
  SheetClose,
  SheetOverlay,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
  HoverCard,
  HoverCardTrigger,
  HoverCardContent,
  CardDecorator,
  Progress,
  Slider,
  LoadingSpinner,
  Skeleton,
  CardSkeleton,
  TableSkeleton,
  ErrorBoundary,
  ErrorFallback,
  useErrorHandler,
  Calendar,
  DatePicker,
  DatePickerRange,
  Sidebar,
  Header,
  Navbar,
  ResponsiveDialog,
  Pagination,
  Tabs,
  TabsWithContainer,
  TabsRoot,
  TabsList,
  TabsTrigger,
  TabsContent,
  CollapsibleSection,
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent,
  ChartStyle,
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormDescription,
  FormMessage,
  useFormField,
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuContent,
  NavigationMenuTrigger,
  NavigationMenuLink,
  NavigationMenuIndicator,
  NavigationMenuViewport,
  navigationMenuTriggerClass,
  ThemeToggleIcon,
  // Tooltip (simple)
  ButtonTooltip,
  Tooltip,
  // Tooltip (Radix primitives)
  RadixTooltip,
  RadixTooltipTrigger,
  RadixTooltipContent,
  RadixTooltipProvider,
  Separator,
  Kbd,
  Label,
  Text,
  Heading,
  Lead,
  Small,
  Muted,
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandSeparator,
  CommandShortcut,
  ScrollArea,
  ScrollBar,
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
  Toggle,
  toggleVariants,
  Toaster,
  toast,
  toastSemantic,
  SelectRoot,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  Icon,
  createIcon,
  DropdownProfile,
} from './ui-primitives'
export type {
  AccordionGroupProps,
  AccordionGroupItem,
  AccordionGroupSingleProps,
  AccordionGroupMultipleProps,
  AccordionProps,
  AlertProps,
  AlertVariant,
  AvatarProps,
  AvatarImageProps,
  AvatarFallbackProps,
  AvatarFallbackVariant,
  AvatarBadgeProps,
  AvatarBadgeVariant,
  AvatarSize,
  AvatarGroupProps,
  AvatarGroupOverlap,
  AvatarGroupCountProps,
  BadgeProps,
  BadgeVariant,
  BadgeSize,
  BreadcrumbProps,
  BreadcrumbItem,
  BreadcrumbSeparator,
  ButtonProps,
  ButtonVariant,
  ButtonSize,
  ButtonGroupProps,
  ButtonGroupItemProps,
  ButtonGroupSeparatorProps,
  ButtonGroupOrientation,
  ToggleGroupProps,
  ToggleGroupItemProps,
  ToggleGroupType,
  ToggleGroupOrientation,
  ChipProps,
  ChipSize,
  ChipVariant,
  InputProps,
  InputOTPProps,
  InputOTPGroupProps,
  InputOTPSeparatorProps,
  InputOTPSeparatorOrientation,
  InputOTPSlotProps,
  InputOTPSlotVariant,
  InputOTPSingleProps,
  InputOTPSize,
  FileInputProps,
  InputGroupProps,
  InputGroupAddonProps,
  InputGroupAddonAlign,
  InputGroupInputProps,
  InputGroupTextareaProps,
  CheckboxProps,
  RadioProps,
  RadioGroupProps,
  RadioGroupItemProps,
  SwitchProps,
  SelectProps,
  NativeSelectProps,
  NativeSelectSize,
  FieldProps,
  EmptyProps,
  CarouselApi,
  CarouselOptions,
  CarouselPlugin,
  CarouselProps,
  CarouselContentProps,
  CarouselItemProps,
  CarouselPreviousProps,
  CarouselNextProps,
  AspectRatioProps,
  AspectRatioPreset,
  ComboboxProps,
  ComboboxOption,
  KbdProps,
  TextProps,
  HeadingProps,
  HeadingLevel,
  MenubarProps,
  MenubarMenuProps,
  MenubarTriggerProps,
  MenubarContentProps,
  MenubarItemProps,
  MenubarCheckboxItemProps,
  MenubarRadioGroupProps,
  MenubarRadioItemProps,
  MenubarLabelProps,
  MenubarSeparatorProps,
  MenubarSubProps,
  MenubarSubTriggerProps,
  MenubarSubContentProps,
  ContextMenuProps,
  ContextMenuTriggerProps,
  ContextMenuContentProps,
  ContextMenuItemProps,
  ContextMenuCheckboxItemProps,
  ContextMenuRadioGroupProps,
  ContextMenuRadioItemProps,
  ContextMenuLabelProps,
  ContextMenuSeparatorProps,
  ContextMenuSubProps,
  ContextMenuSubTriggerProps,
  ContextMenuSubContentProps,
  TextareaProps,
  TextareaSize,
  RichTextEditorProps,
  RichTextEditorSize,
  DropdownSelectProps,
  DropdownOption,
  DropdownAlign,
  DropdownMenuAlign,
  DropdownIconMenuProps,
  DropdownMenuActionProps,
  DropdownMenuProps,
  DropdownMenuTriggerProps,
  DropdownMenuPortalProps,
  DropdownMenuContentProps,
  DropdownMenuGroupProps,
  DropdownMenuLabelProps,
  DropdownMenuItemProps,
  DropdownMenuCheckboxItemProps,
  DropdownMenuRadioGroupProps,
  DropdownMenuRadioItemProps,
  DropdownMenuSeparatorProps,
  DropdownMenuSubProps,
  DropdownMenuSubTriggerProps,
  DropdownMenuSubContentProps,
  PopoverProps,
  PopoverTriggerProps,
  PopoverAnchorProps,
  PopoverContentProps,
  AlertDialogProps,
  AlertDialogTriggerProps,
  AlertDialogContentProps,
  AlertDialogHeaderProps,
  AlertDialogFooterProps,
  AlertDialogTitleProps,
  AlertDialogDescriptionProps,
  AlertDialogActionProps,
  AlertDialogCancelProps,
  DialogProps,
  DialogTriggerProps,
  DialogPortalProps,
  DialogCloseProps,
  DialogOverlayProps,
  DialogContentProps,
  DialogHeaderProps,
  DialogFooterProps,
  DialogTitleProps,
  DialogDescriptionProps,
  DrawerProps,
  DrawerTriggerProps,
  DrawerPortalProps,
  DrawerCloseProps,
  DrawerOverlayProps,
  DrawerContentProps,
  DrawerHeaderProps,
  DrawerFooterProps,
  DrawerTitleProps,
  DrawerDescriptionProps,
  ModalProps,
  ModalSize,
  SheetProps,
  SheetTriggerProps,
  SheetPortalProps,
  SheetCloseProps,
  SheetOverlayProps,
  SheetContentProps,
  SheetContentSide,
  SheetHeaderProps,
  SheetFooterProps,
  SheetTitleProps,
  SheetDescriptionProps,
  TableProps,
  TableHeaderProps,
  TableBodyProps,
  TableFooterProps,
  TableRowProps,
  TableHeadProps,
  TableCellProps,
  TableCaptionProps,
  HoverCardProps,
  HoverCardTriggerProps,
  HoverCardContentProps,
  CardDecoratorProps,
  ProgressProps,
  ProgressVariant,
  ProgressSize,
  SliderProps,
  SliderVariant,
  SliderSize,
  CardProps,
  ResponsiveDialogProps,
  ResponsiveDrawerDirection,
  ResponsiveDialogMode,
  PaginationProps,
  PaginationVariant,
  TabsWithContainerItem,
  SkeletonProps,
  SkeletonTone,
  SkeletonRadius,
  SkeletonLineSize,
  TabsRootProps,
  TabsListProps,
  TabsTriggerProps,
  TabsContentProps,
  SeparatorProps,
  LabelProps,
  CommandProps,
  CommandDialogProps,
  ScrollAreaProps,
  ScrollAreaViewportProps,
  ScrollBarProps,
  ResizablePanelGroupProps,
  ResizablePanelProps,
  ResizableHandleProps,
  ToggleProps,
  ToggleSize,
  ToggleVariant,
  ToasterProps,
  SelectRootProps,
  SelectTriggerProps,
  SelectContentProps,
  SelectItemProps,
  SelectLabelProps,
  SelectSeparatorProps,
  TooltipProps,
  ButtonTooltipProps,
  RadixTooltipProps,
  RadixTooltipTriggerProps,
  RadixTooltipContentProps,
  RadixTooltipProviderProps,
  IconProps,
  DropdownProfileProps,
  DatePickerProps,
  DatePickerRangeProps,
  ChartConfig,
} from './ui-primitives'

// Icon constants
export {
  ICON_DEFAULT_SIZE,
  ICON_DEFAULT_STROKE_WIDTH,
  ICON_SIZES,
} from './lib/icon-constants'
export type { IconSize } from './lib/icon-constants'

// Phase C: design-system sections (root-level re-export for reliable resolution from consumers' node_modules)
export { Header as SectionHeader } from './section-primitives'
export type { HeaderProps as SectionHeaderProps, HeaderLink } from './section-primitives'

// Phase C: design-system layouts (root-level re-export for reliable resolution from consumers' node_modules)
export { Container, Page, Section, Grid, Stack } from './layout-primitives'
export type { ContainerProps, PageProps, SectionProps, GridProps, StackProps } from './layout-primitives'
